spring:
  application:
    name: registry-service

server:
  port: 9999

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:9999/eureka